### ISSUE TITLE
Windows 8.1

### ISSUE THREAD

**Issue by marphy-sk** [WebReflection/node-gtk#23]
Have you sam tip haw implement on windows ? 
I have all important class and msys32, mingw .... visual expres studio etc, but 
node-pre-gyp with msbuild cannot find glib.h and girepository.h

**Comment by marphy-sk** [comment]
../src/loop.cc(4): fatal error C1083: Cannot open include file: 'glib.h': No such file or directory [C:\Users\Marian\AppData\Roaming\npm\node_modules\node-gtk\build\node-gtk.vcxproj]

**Comment by WebReflection** [comment]
I think you need to have a running Gtk+ first in there:
http://www.gtk.org/download/windows.php

The idea is to create pre-built modules once we move forward a little bit. There will be hopefully both 64 and 32 bit modules but right now it's a bit early for this ... it doesn't even build on OSX so maybe you want to wait a little bit for this.

I'll keep it open for now unless @magcius wants to keep the bug-log clean of "distractions"

**Comment by WebReflection** [comment]
FYI I've started adjusting and verifying things here and there in order to make this build on Windows too.

Here the current error status: https://github.com/WebReflection/node-gtk/issues/24

Here instructions on how to try building on Windows:
https://github.com/WebReflection/node-gtk#how-to-build-on-windows-experimental
