### ISSUE TITLE
FunctionInvoker wrongly asserts value->IsArray()

### ISSUE THREAD

**Issue by romgrk** [WebReflection/node-gtk#27]
I might be mistaken on this, but it seems to me that the value here:

https://github.com/WebReflection/node-gtk/blob/master/src/function.cc#L132

can be a string, and therefore shouldn't automatically call `GetArrayLength()` at:

https://github.com/WebReflection/node-gtk/blob/master/src/function.cc#L35

(The assertion is correct, of course, the assumption is not. I think.)

**Comment by WebReflection** [comment]
FYI this project is half abandoned due lack of support for the C++ side.

If you don't have strong dependencies on all nodejs cores you could give [jsgtk](https://github.com/WebReflection/jsgtk) a try.

**Comment by romgrk** [comment]
Yes I know, magcius busy. (see, I dont tag his name so he doesnt get pings :D )

I just wanted to document in case someone has interest. Also I couldn't resolve to just let go of this module because of some lack of knowledge; therefore, I have decided to complete it myself. Whilst learning C/C++. And GLib. And V8. Very interesting.
(see https://github.com/romgrk/node-gtk/tree/uggly )
The branch name reflects what I think of it, but it manages to solve some of the issues on this repo. Namely, support interfaces, expose boxeds. And some more.

I think it shouldn't be so hard to have a complete working version of this. (free inspiration:  https://github.com/GNOME/seed and https://github.com/GNOME/gjs)
The hard part is having a correct version of this.

**Comment by magcius** [comment]
I've been pushing to get some time / other people looking at it, since I do think it's important enough as a project, but it's strictly a weekend project for me right now (and my weekends have mostly been going to not-coding projects at this point)

**Comment by WebReflection** [comment]
@romgrk FWIW this issue is most likely the reason there are problems in OSX with more complex scenarios (Webkit demo, as example) but feel free to PR here whatever you want to move forward.

I'm actually hoping for some help like this.

Regarding your free inspiration, consider I'm moving forward at "speed-light" via JS only on [jsgtk](https://github.com/WebReflection/jsgtk/) so that examples look [fully node.js compatible](https://github.com/WebReflection/jsgtk/blob/master/examples/hello-world.js), the _CommonJS_ module loader works with any _npm_ already (well, any npm up to GJS syntax) https://github.com/WebReflection/jsgtk/blob/master/examples/hello-world.js and the entire namespace is already exposed `camelCase` via `GIRespotiroty` and introspection.

It works already in OSX and this is the better list of features so far:
https://github.com/WebReflection/jsgtk#project-ideas

This is the list of node.js core modules, some of them are exactly **the** nodejs core module:
https://github.com/WebReflection/jsgtk/tree/master/jsgtk_modules

You don't need to throw errors around to know `__dirname` or `__filename` and you also always have the `process.cwd()` in case is needed:
https://github.com/WebReflection/jsgtk/blob/master/examples/base.js

`require` loads absolute urls as well as relative or globally installed, and I'm planning to make every example in here compatible (and simplified) with jsgtk.

First example:

GJS: https://github.com/optimisme/gjs-examples/blob/master/egCss.js
JSGtk: https://github.com/WebReflection/gjs-examples/blob/master/egCss.js

Specially note the `getAppFileInfo` in the GJS version ... what a way to handle program paths :-)

**Comment by romgrk** [comment]
> Specially note the getAppFileInfo in the GJS version ... what a way to handle program paths :-)

LOL yes, I have that copied on top of quite a few files.

> FWIW this issue is most likely the reason there are problems in OSX with more complex scenarios (Webkit demo, as example) 

Shouldn't be so hard to fix, shouldn't it? How I understood this issue is that it is a problem of semantic interpretation of the different types of arguments and values being passed around.  (e.g. I noticed this when trying to pass a v8::String value to GI; the invoker tries to fill in the “array”-length in-parameter, as it does for all C-types arrays, but the array is a string.) (important note to self: use -1 instead of string.length?)

Interesting work with the JsGtk, but I feel having a node-_like_ interface isn't the correct solution. I'd rather have Node with Gtk. As an example, my uggly branch has a file I use for tests (https://github.com/romgrk/node-gtk/blob/uggly/test/index.coffee) which defines a code editor UI with Gtk widgets, but where I use node modules for file saving/loading. It feels reaally powerful to be able to combine both so easily. 

> JSGtk: https://github.com/WebReflection/gjs-examples/blob/master/egCss.js

OH GOD, the camelCase syntax feels so pretty after a few days working with horrible_c_snake_syntax! Doing that next.

**Comment by WebReflection** [comment]
> I use node modules for file saving/loading. It feels reaally powerful to be able to combine both so easily.

Core modules such `require("fs")` and `require("path")` works on _JSGtk_ already, the latter one is a full 1:1 implementation, the `require("fs")` though is not fully complete.

To be clear about the GJS goal: it wants to do exactly what we are doing in here => same exact achievement but based on GJS instead of node.js

Ideally everyone would love to have a `camelCase` **Gtk3** on _Node.JS_, but it's going to take forever and there are few attempts that already failed.

To make this happens sooner than later, I can use `gjs` which is already well distributed and supported in Linux and OSX and it doesn't require any build step, which is also a plus for embedded ARM/MIPS platforms.

Ideally, everything that will work on _JSGtk_ will also work on _node-gtk_ if this will ever see the light ... but since like you I don't like being stuck but I love this idea (as well as Gtk3 which is my default Desktop GNOME UI) I've decided to be patience here and move on there as I can.

For instance, implementing `camelCase` the right way has been (still is) a challenge once we're ready here I can mostly copy and paste ;-)

So, again, please send PR here and let's hope magcious will find time or be supported to work on this a bit more.

Best Regards
