### ISSUE TITLE
Make it more "JavaScripty"

### ISSUE THREAD

**Issue by WebReflection** [WebReflection/node-gtk#4]
In JavaScript and modern ES2015 class declaration, methods as well as properties getters and setters, are **not enumerable** but **configurable** .

``` js
(function () {'use strict';
  class A {
    static public () {}
    method() {}
    get prop() {}
  }

  console.log(Object.getOwnPropertyDescriptor(A, 'public'));
  console.log(Object.getOwnPropertyDescriptor(A.prototype, 'method'));
  console.log(Object.getOwnPropertyDescriptor(A.prototype, 'prop'));

}());
```

Accordingly, [these two operations](https://github.com/WebReflection/node-gtk/blob/master/lib/index.js#L16-L19) should probably be based on `Object.defineProperty` which has been used [later on](https://github.com/WebReflection/node-gtk/blob/master/lib/index.js#L71-L75) in an opposite way than it should be (which is configurable and not enumerable).
### camelCase instead of Ruby_case

In [this line](https://github.com/WebReflection/node-gtk/blob/master/lib/index.js#L69) properties with hyphens `-` on their name will be converted into `_`

I've asked about this already in the GNOME JavaScript ML and it looks like GJS as well as Seed did a mistake believing that JavaScript uses ruby_case notation and the [HowToWriteALanguageBinding GNOME page](https://wiki.gnome.org/Projects/GObjectIntrospection/HowToWriteALanguageBinding) states it should be familiar with the language. However, Java got it right but for some reason JS didn't.

I've built the entire GNOME locally in order to be able to automate the generation of this file through each `gir` info I could think of:
https://github.com/WebReflection/jsgtk/blob/master/jsgtk/gi.js

Since Proxies are nowhere in V8, and these are not transparent in SpiderMonkey 24, that generation ensures that in GJS I can use per each class method and each class property a `camelCase` version, delegating entirely to GJS ruby_case.

Looking at the current code, and since we are somehow delegating everything anyway, we could intercept upfront all `ruby_cased` methods and properties and define them with the right JS name.

We could either choose to duplicate and have both versions initially or simply drop the ruby_case and make this project more friendly for JS developers.

This is/was apparently [an idea goal in node-gir](https://github.com/creationix/node-gir#api-ideas) too and since I've complained about ruby_case, node-gir complained about ruby_cased, I wonder if we should just stop complaining and make it happen at this early stage.

What do you think? I wouldn't mind having internally the `_gir` reflecting 1:1 the C name but as exposed API we could do better.

``` js
// with a simple utility like this one
function toCamelCase(key) {
  return key.replace(/[_-]([a-z])/g, function ($0, $1) {
    return $1.toUpperCase();
  });
}

// ...
// we could improve the properties assignment as such:

        Object.defineProperty(constructor.prototype, toCamelCase(propertyName), {
            configuraable: true,
            get: propertyGetter(propertyName),
            set: propertySetter(propertyName),
        });


// also improving classes
function declareFunction(obj, info) {
    var name = toCamelCase(_gir.BaseInfo_get_name.call(info));
    var flags = _gir.function_info_get_flags(info);
    var func = _gi.MakeFunction(info);
    var target = flags & GIRepository.FunctionInfoFlags.IS_METHOD ?
      obj.prototype : obj;
    Object.defineProperty(target, name, {
      configurable: true,
      writable: true,
      value: func
    });
}
```

I'll create a camel-case branch and push it so that we could  play around with it.
### repeated imports ?

I have the feeling that right now we are importing multiple time doing multiple time same operations per each namespace. If I've got it right, we should probably improve here.

``` js
var NS = Object.create(null); // <== avoid name clashes
exports.importNS = function(ns, version) {
    if (!version) version = 'default';
    if (!(ns in NS)) NS[ns] = {};
    if (!(version in NS[ns])) NS[ns][version] = importNS(ns, version);
    return NS[ns][version];
};
```

thoughts ?

Regards

**Comment by magcius** [comment]
> enumerable but configurable

Sure. I just didn't look close enough. See here: https://github.com/WebReflection/node-gtk/blob/master/lib/index.js#L44

Should be easy enough to change

> camel case

First off, JS has no official style guide. Some people prefer `snake_case`, some prefer `camelCase`, some even prefer `MuleCase` or whatever they call that one. I've seen all three in major JS codebases.

Second, gjs does try to translate `fooBar` to `foo_bar`, at least for properties. I think it was one of our biggest mistakes. Most people ended up using the `foo_bar` version anyway, since that's what was in the documentation.

I don't think the style is as important as it is. And it makes switching from gjs a lot better, and you're able to translate code samples from other languages more easily, etc.

> repeated imports

Yeah, we need to cache things in `importNS`. There's some other baggage there I need to clean up before I can do that one.

**Comment by WebReflection** [comment]
I haven't make my camelCase version of GJS imported automatically in `jsgtk` because I agreed in the same/related ML having documentation and copy/paste example easy to use and test was superior than style, **however** I can't disagree more on the following:

> First off, JS has no official style guide.

Apparently one of the biggest mistake every new JS comer is to not read the ECMAScript specification where in its entirety there's not a single method or property named in a `ruby_case`.

This is just [ES2015 Specification](http://www.ecma-international.org/ecma-262/6.0/) but even the most  universally deployed one since ever, the 3rd Edition, and the 5 or 5.1 one, never ever introduced a single method or property named with an underscore.

The same goes for W3C DOM specifications that are implemented indeed in Java.

So, one point to be clear: whoever implemented `ruby_case` naming convention in any project or library was coming from  another world and wasn't familiar enough with the JS one.

Apologies for the long clarification, but I've been coding JS for 11 years now, I think I've seen them all and kinda know both trends and I know by heart most specifications.

**Comment by romgrk** [comment]
I'll give you my opinion as an end-user of what `node-gtk` aims to be (on the camelCase aspect):

One of the main points that got me looking into something else than `GJS` was the fact that it felt way too close to writing C directly. Having another version of `GJS` or `Seed` isn't interesting.

Also, the main advantage of writing Node bindings is to integrate with `NPM` ecosystem. Having the bindings written using `snake_case` and some other packages using `camelCase` doesn't feel harmonious. And unharmonious code isn't attractive.

E.g. here an example https://github.com/neovim/node-client ; this looks attractive. 

(Therefore I vote for camelCase)

**Comment by benwaffle** [comment]
I think it partially depends on the goal of this project. If it is to make the GNOME stack more attractive to outsiders, then use camelCase. If it is just to run GNOME JS code on a different engine, then use ruby_case.

As for making it more javascript-y
- signals should be connected like `button.on('clicked', ...)`.
- Constructors shouldn't take an object of properties. just export the constructors from C code and have a no-arg constructor use `g_object_new` if not provided
- automatically convert GValues
- map GObject properties to javascript properties
  - use the conventional 'notify::property' for change notifications
- GErrors should become exceptions

It would be nice if we could hack `require()` to provide something like `require('gir:Gtk')`. We could also just export a function `require('node-gtk')('Gtk')`

**Comment by magcius** [comment]
I would be OK with it if it was properly documented, and the conversion rules were standard.

A big area that hit us in gjs was not having proper documentation, so I would want to make sure any changes we add would be properly documented, and the translation rules wouldn't be too hard.

As for naming schemes, most people will probably be looking at the `foo-bar` property in the C code. `foo_bar` is a pretty acceptable transformation rule to do in your head, whereas I think `fooBar` is a bit weirder, especially with all the special cases. Additionally, you'd still connect to `notify::foo-bar` signals unless we special cased the notify signal (but that would miss other complex detailed signals as well). I don't think it's worth the amount of pain.

We already convert GValues, GErrors should already become exceptions, etc.

The argument between exposing generic constructors and exposing e.g. `gtk_widget_new` is more complex. There are already some cases like `gtk_checkbox_new` and `gtk_checkbox_new_with_label` and such, which mirror nicely in C, but would become `new Gtk.Checkbox` and `Gtk.Checkbox.new_with_label` with your proposal. I would prefer to keep the existing constructor syntax for property-based construction, and move constructor functions to `Gtk.Checkbox.new`. Though it is confusing.

As for `require('gir:Gtk')`, you can't do that with Node -- Node doesn't allow you to hack the `require` syntax like that. Additionally, `require('node-gtk')` returning a function isn't acceptable to me, because we might have other functions exported like `startLoop`.

**Comment by benwaffle** [comment]
you can do 

``` JS
module.exports = function () { ... }
module.exports.startLoop = function () { ... }
```

and

``` JS
const idk = require('idk');
idk();
idk.startLoop();
```

and i guess there is no way to do `new Gtk.Checkbox.with_label` like in vala?

**Comment by magcius** [comment]
We could do that, but I don't like that API proposal. Seems bizarre and foreign to me.

**Comment by benwaffle** [comment]
I think it is pretty common among node modules
It doesn't look too bad

``` JS
const gir = require('./lib/');
const Gtk = gir('Gtk');

gir.startLoop();
```

**Comment by benwaffle** [comment]
Can we do something like https://jsfiddle.net/LjL5rc4p/2/ for named constructors?

**Comment by magcius** [comment]
So, a few comments on that. First, transforming `Foo.new_with_bar` to `new Foo.with_bar` isn't guaranteed. While most constructors have `new_` in their name, some don't -- I know of one library that uses `create_with_bar`. Assuming we simply chop out the `new_`, that would make the secondary constructor `new Foo.create_with_bar`, which seems awkward to me.

Additionally, constructor functions may be async, constructor objects in JS are guaranteed to return an object. So users would have to call `Foo.new_async` anyway, not `new Foo.async`. So that's another edge case.

The more we add exceptions to our translation rules (translate from `gtk_widget_new_with_bar` to `new Gtk.Widget.with_bar` by stripping new, unless it's an async constructor, or it throws an error, or it returns a different object than an `Gtk.Widget`), the difficult it is for the API to grasp.

gjs had much simpler translation rules, and from maintaining it, seeing bug reports, seeing mailing list posts and StackOverflow questions, that was already too much to handle.

**Comment by magcius** [comment]
Basically, we have many options, but you have to realize that each option is a choice, it's a tradeoff, and what we're doing is complex, automated, API design. I would much, much prefer to err on the side of conservative, understandable transformation rules for now.

Our API design is always going to be a mix of node and GNOME, and that's never going to change. Our project is effectively a project to link the node and GNOME communities together, so we can use code from both projects together.

I would be OK with a series of helper modules similar to what Bluebird has, in which users apply these transformations in an opt-in manner. Perhaps allowing the users to opt-in to piecemeal transformations is an OK compromise, since users might be able to grasp the individual transformations better if they are the ones applying them.

**Comment by magcius** [comment]
I'm going to close this issue for now, but if someone wants to work on these transformation modules, as long as they are optional, please file new PRs and issues for them, and I'll include them.

As for the main-function extending entry-point, I don't know any node modules that do this, and I myself prefer the explicitness of `importNS`, but I'm open to suggestion if you think `importNS` would turn traditional node communities off. I'm not too familiar with `node` conventions. A Google didn't turn up anything, though.

**Comment by WebReflection** [comment]
@magcius 

> I would be OK with it if it was properly documented, and the conversion rules were standard.

Documentation about GJS is basically indirectly retrieved from the Python GTK one where Python developers are fine and used to ruby_like naming  convention and/or vice-versa.

In JS you have  the entirety of every ECMAScript Specification and W3C or WHATWG one to understand that every single API is camelCase so `fooBar` instead of `foo_bar` won't be a surprise to anyone in the JS community.

If this project is about bringing GNOME and GJS or Seed closer to JS developers, we should probably ask ourselves how come with poor documentation and unfriendly API that didn't happen.

Plus some unnecessary complication in OSX as a target, and the ability to generate GJS documentation like mentioned in the GNOME page.

No, I'd say the problem isn't exactly having `foo_bar` so that everyone knows what's  going on but hey, I really just discovered all this few weeks ago, amused by the fact nobody knows in the JS community about all GTK3 and its bindings potentials out there.

Just my 2 cents

**Comment by benwaffle** [comment]
I hope this project is about helping node and JS devs to use GNOME & GTK

**Comment by kidwm** [comment]
@magcius 

> but if someone wants to work on these transformation modules, as long as they are optional, please file new PRs and issues for them, and I'll include them.

It is possible to write a babel plug-in to do this transformation, so that would not be a big problem.

https://github.com/thejameskyle/babel-plugin-handbook

And I would like to use `require('node-gtk')('Gtk')` for import syntax.
